ext {
    extName = 'ArabsHentai'
    extClass = '.ArabsHentai'
    themePkg = 'dooplay'
    extVersionCode = 29
    overrideVersionCode = 29
    baseUrl = 'https://arabshentai.net'
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(':lib:playlistutils'))
    implementation(project(':lib:doodextractor'))
    implementation(project(':lib:mixdropextractor'))
    implementation(project(':lib:streamwishextractor'))
    implementation(project(':lib:streamtapeextractor'))
    implementation(project(':lib:voeextractor'))
    implementation(project(':lib:uqloadextractor'))
    implementation(project(':lib:universalextractor'))
}
